export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_SIGNOUT = 'USER_SIGNOUT';

export const UPDATE_ORDERITEM_REQUEST = 'UPDATE_ORDERITEM_REQUEST';
export const UPDATE_ORDERITEM_REQUEST_SUCCESS = 'UPDATE_ORDERITEM_REQUEST_SUCCESS';
export const UPDATE_ORDERITEM_REQUEST_FAIL = 'UPDATE_ORDERITEM_REQUEST_FAIL';
export const UPDATE_ORDERITEM_RESET = 'UPDATE_ORDERITEM_RESET';
